create table sys_job_log
(
    job_log_id     bigint auto_increment comment '任务日志ID'
        primary key,
    job_name       varchar(64)               not null comment '任务名称',
    job_group      varchar(64)               not null comment '任务组名',
    invoke_target  varchar(500)              not null comment '调用目标字符串',
    job_message    varchar(500)              null comment '日志信息',
    status         char          default '0' null comment '执行状态（0正常 1失败）',
    exception_info varchar(2000) default ''  null comment '异常信息',
    create_time    datetime                  null comment '创建时间'
)
    comment '定时任务调度日志表' collate = utf8mb4_general_ci
                                 row_format = DYNAMIC;

INSERT INTO wms.sys_job_log (job_log_id, job_name, job_group, invoke_target, job_message, status, exception_info, create_time) VALUES (1, '库存预警检查', 'SYSTEM', 'stockWarningTask.checkStockWarning', '库存预警检查 总共耗时：320毫秒', '0', '', '2026-04-08 10:30:00');
INSERT INTO wms.sys_job_log (job_log_id, job_name, job_group, invoke_target, job_message, status, exception_info, create_time) VALUES (2, '库存预警检查', 'SYSTEM', 'stockWarningTask.checkStockWarning', '库存预警检查 总共耗时：38毫秒', '0', '', '2026-04-08 11:30:00');
INSERT INTO wms.sys_job_log (job_log_id, job_name, job_group, invoke_target, job_message, status, exception_info, create_time) VALUES (3, '库存预警检查', 'SYSTEM', 'stockWarningTask.checkStockWarning', '库存预警检查 总共耗时：47毫秒', '0', '', '2026-04-08 12:00:00');
INSERT INTO wms.sys_job_log (job_log_id, job_name, job_group, invoke_target, job_message, status, exception_info, create_time) VALUES (4, '库存预警检查', 'SYSTEM', 'stockWarningTask.checkStockWarning', '库存预警检查 总共耗时：20毫秒', '0', '', '2026-04-08 12:30:00');
INSERT INTO wms.sys_job_log (job_log_id, job_name, job_group, invoke_target, job_message, status, exception_info, create_time) VALUES (5, '库存预警检查', 'SYSTEM', 'stockWarningTask.checkStockWarning', '库存预警检查 总共耗时：15毫秒', '0', '', '2026-04-08 13:00:00');
INSERT INTO wms.sys_job_log (job_log_id, job_name, job_group, invoke_target, job_message, status, exception_info, create_time) VALUES (6, '库存预警检查', 'SYSTEM', 'stockWarningTask.checkStockWarning', '库存预警检查 总共耗时：21毫秒', '0', '', '2026-04-08 13:30:00');
INSERT INTO wms.sys_job_log (job_log_id, job_name, job_group, invoke_target, job_message, status, exception_info, create_time) VALUES (7, '库存预警检查', 'SYSTEM', 'stockWarningTask.checkStockWarning', '库存预警检查 总共耗时：34毫秒', '0', '', '2026-04-08 14:00:00');
INSERT INTO wms.sys_job_log (job_log_id, job_name, job_group, invoke_target, job_message, status, exception_info, create_time) VALUES (8, '库存预警检查', 'SYSTEM', 'stockWarningTask.checkStockWarning', '库存预警检查 总共耗时：28毫秒', '0', '', '2026-04-08 14:30:00');
INSERT INTO wms.sys_job_log (job_log_id, job_name, job_group, invoke_target, job_message, status, exception_info, create_time) VALUES (9, '库存预警检查', 'SYSTEM', 'stockWarningTask.checkStockWarning', '库存预警检查 总共耗时：37毫秒', '0', '', '2026-04-08 15:00:00');
INSERT INTO wms.sys_job_log (job_log_id, job_name, job_group, invoke_target, job_message, status, exception_info, create_time) VALUES (10, '库存预警检查', 'SYSTEM', 'stockWarningTask.checkStockWarning', '库存预警检查 总共耗时：114毫秒', '0', '', '2026-04-08 15:30:00');
INSERT INTO wms.sys_job_log (job_log_id, job_name, job_group, invoke_target, job_message, status, exception_info, create_time) VALUES (11, '库存预警检查', 'SYSTEM', 'stockWarningTask.checkStockWarning', '库存预警检查 总共耗时：91毫秒', '0', '', '2026-04-08 16:00:00');
INSERT INTO wms.sys_job_log (job_log_id, job_name, job_group, invoke_target, job_message, status, exception_info, create_time) VALUES (12, '库存预警检查', 'SYSTEM', 'stockWarningTask.checkStockWarning', '库存预警检查 总共耗时：160毫秒', '0', '', '2026-04-08 16:30:00');
INSERT INTO wms.sys_job_log (job_log_id, job_name, job_group, invoke_target, job_message, status, exception_info, create_time) VALUES (13, '库存预警检查', 'SYSTEM', 'stockWarningTask.checkStockWarning', '库存预警检查 总共耗时：24毫秒', '0', '', '2026-04-08 17:00:00');
INSERT INTO wms.sys_job_log (job_log_id, job_name, job_group, invoke_target, job_message, status, exception_info, create_time) VALUES (14, '库存预警检查', 'SYSTEM', 'stockWarningTask.checkStockWarning', '库存预警检查 总共耗时：523毫秒', '0', '', '2026-04-08 17:30:00');
INSERT INTO wms.sys_job_log (job_log_id, job_name, job_group, invoke_target, job_message, status, exception_info, create_time) VALUES (15, '库存预警检查', 'SYSTEM', 'stockWarningTask.checkStockWarning', '库存预警检查 总共耗时：35毫秒', '0', '', '2026-04-08 18:00:00');
INSERT INTO wms.sys_job_log (job_log_id, job_name, job_group, invoke_target, job_message, status, exception_info, create_time) VALUES (16, '库存预警检查', 'SYSTEM', 'stockWarningTask.checkStockWarning', '库存预警检查 总共耗时：45毫秒', '0', '', '2026-04-08 18:30:00');
INSERT INTO wms.sys_job_log (job_log_id, job_name, job_group, invoke_target, job_message, status, exception_info, create_time) VALUES (17, '库存预警检查', 'SYSTEM', 'stockWarningTask.checkStockWarning', '库存预警检查 总共耗时：15毫秒', '0', '', '2026-04-09 17:30:00');
INSERT INTO wms.sys_job_log (job_log_id, job_name, job_group, invoke_target, job_message, status, exception_info, create_time) VALUES (18, '库存预警检查', 'SYSTEM', 'stockWarningTask.checkStockWarning', '库存预警检查 总共耗时：35毫秒', '0', '', '2026-04-09 18:00:00');
INSERT INTO wms.sys_job_log (job_log_id, job_name, job_group, invoke_target, job_message, status, exception_info, create_time) VALUES (19, '库存预警检查', 'SYSTEM', 'stockWarningTask.checkStockWarning', '库存预警检查 总共耗时：8毫秒', '0', '', '2026-04-09 18:30:00');
INSERT INTO wms.sys_job_log (job_log_id, job_name, job_group, invoke_target, job_message, status, exception_info, create_time) VALUES (20, '库存预警检查', 'SYSTEM', 'stockWarningTask.checkStockWarning', '库存预警检查 总共耗时：31毫秒', '0', '', '2026-04-09 20:30:00');
INSERT INTO wms.sys_job_log (job_log_id, job_name, job_group, invoke_target, job_message, status, exception_info, create_time) VALUES (21, '库存预警检查', 'SYSTEM', 'stockWarningTask.checkStockWarning', '库存预警检查 总共耗时：30毫秒', '0', '', '2026-04-09 21:00:00');
INSERT INTO wms.sys_job_log (job_log_id, job_name, job_group, invoke_target, job_message, status, exception_info, create_time) VALUES (22, '库存预警检查', 'SYSTEM', 'stockWarningTask.checkStockWarning', '库存预警检查 总共耗时：18毫秒', '0', '', '2026-04-09 21:30:00');
INSERT INTO wms.sys_job_log (job_log_id, job_name, job_group, invoke_target, job_message, status, exception_info, create_time) VALUES (23, '库存预警检查', 'SYSTEM', 'stockWarningTask.checkStockWarning', '库存预警检查 总共耗时：31毫秒', '0', '', '2026-04-09 22:30:00');
INSERT INTO wms.sys_job_log (job_log_id, job_name, job_group, invoke_target, job_message, status, exception_info, create_time) VALUES (24, '库存预警检查', 'SYSTEM', 'stockWarningTask.checkStockWarning', '库存预警检查 总共耗时：37毫秒', '0', '', '2026-04-09 23:00:00');
INSERT INTO wms.sys_job_log (job_log_id, job_name, job_group, invoke_target, job_message, status, exception_info, create_time) VALUES (25, '库存预警检查', 'SYSTEM', 'stockWarningTask.checkStockWarning', '库存预警检查 总共耗时：50毫秒', '0', '', '2026-04-10 00:00:00');
INSERT INTO wms.sys_job_log (job_log_id, job_name, job_group, invoke_target, job_message, status, exception_info, create_time) VALUES (26, '库存预警检查', 'SYSTEM', 'stockWarningTask.checkStockWarning', '库存预警检查 总共耗时：21毫秒', '0', '', '2026-04-10 00:30:00');
INSERT INTO wms.sys_job_log (job_log_id, job_name, job_group, invoke_target, job_message, status, exception_info, create_time) VALUES (27, '库存预警检查', 'SYSTEM', 'stockWarningTask.checkStockWarning', '库存预警检查 总共耗时：30毫秒', '0', '', '2026-04-10 02:00:00');
INSERT INTO wms.sys_job_log (job_log_id, job_name, job_group, invoke_target, job_message, status, exception_info, create_time) VALUES (28, '库存预警检查', 'SYSTEM', 'stockWarningTask.checkStockWarning', '库存预警检查 总共耗时：30毫秒', '0', '', '2026-04-10 02:30:00');
INSERT INTO wms.sys_job_log (job_log_id, job_name, job_group, invoke_target, job_message, status, exception_info, create_time) VALUES (29, '库存预警检查', 'SYSTEM', 'stockWarningTask.checkStockWarning', '库存预警检查 总共耗时：31毫秒', '0', '', '2026-04-10 03:00:00');
INSERT INTO wms.sys_job_log (job_log_id, job_name, job_group, invoke_target, job_message, status, exception_info, create_time) VALUES (30, '库存预警检查', 'SYSTEM', 'stockWarningTask.checkStockWarning', '库存预警检查 总共耗时：28毫秒', '0', '', '2026-04-10 06:00:00');
INSERT INTO wms.sys_job_log (job_log_id, job_name, job_group, invoke_target, job_message, status, exception_info, create_time) VALUES (31, '库存预警检查', 'SYSTEM', 'stockWarningTask.checkStockWarning', '库存预警检查 总共耗时：38毫秒', '0', '', '2026-04-10 06:30:00');
INSERT INTO wms.sys_job_log (job_log_id, job_name, job_group, invoke_target, job_message, status, exception_info, create_time) VALUES (32, '库存预警检查', 'SYSTEM', 'stockWarningTask.checkStockWarning', '库存预警检查 总共耗时：25毫秒', '0', '', '2026-04-10 07:30:00');
INSERT INTO wms.sys_job_log (job_log_id, job_name, job_group, invoke_target, job_message, status, exception_info, create_time) VALUES (33, '库存预警检查', 'SYSTEM', 'stockWarningTask.checkStockWarning', '库存预警检查 总共耗时：28毫秒', '0', '', '2026-04-10 08:00:00');
INSERT INTO wms.sys_job_log (job_log_id, job_name, job_group, invoke_target, job_message, status, exception_info, create_time) VALUES (34, '库存预警检查', 'SYSTEM', 'stockWarningTask.checkStockWarning', '库存预警检查 总共耗时：24毫秒', '0', '', '2026-04-10 09:00:00');
INSERT INTO wms.sys_job_log (job_log_id, job_name, job_group, invoke_target, job_message, status, exception_info, create_time) VALUES (35, '库存预警检查', 'SYSTEM', 'stockWarningTask.checkStockWarning', '库存预警检查 总共耗时：44毫秒', '0', '', '2026-04-10 14:00:00');
INSERT INTO wms.sys_job_log (job_log_id, job_name, job_group, invoke_target, job_message, status, exception_info, create_time) VALUES (36, '库存预警检查', 'SYSTEM', 'stockWarningTask.checkStockWarning', '库存预警检查 总共耗时：78毫秒', '0', '', '2026-04-10 14:30:00');
INSERT INTO wms.sys_job_log (job_log_id, job_name, job_group, invoke_target, job_message, status, exception_info, create_time) VALUES (37, '库存预警检查', 'SYSTEM', 'stockWarningTask.checkStockWarning', '库存预警检查 总共耗时：66毫秒', '0', '', '2026-04-10 15:00:00');
INSERT INTO wms.sys_job_log (job_log_id, job_name, job_group, invoke_target, job_message, status, exception_info, create_time) VALUES (38, '库存预警检查', 'SYSTEM', 'stockWarningTask.checkStockWarning', '库存预警检查 总共耗时：32毫秒', '0', '', '2026-04-10 15:30:00');
INSERT INTO wms.sys_job_log (job_log_id, job_name, job_group, invoke_target, job_message, status, exception_info, create_time) VALUES (39, '库存预警检查', 'SYSTEM', 'stockWarningTask.checkStockWarning', '库存预警检查 总共耗时：38毫秒', '0', '', '2026-04-10 16:00:00');
INSERT INTO wms.sys_job_log (job_log_id, job_name, job_group, invoke_target, job_message, status, exception_info, create_time) VALUES (40, '库存预警检查', 'SYSTEM', 'stockWarningTask.checkStockWarning', '库存预警检查 总共耗时：41毫秒', '0', '', '2026-04-10 16:30:00');
INSERT INTO wms.sys_job_log (job_log_id, job_name, job_group, invoke_target, job_message, status, exception_info, create_time) VALUES (41, '库存预警检查', 'SYSTEM', 'stockWarningTask.checkStockWarning', '库存预警检查 总共耗时：26毫秒', '0', '', '2026-04-10 17:00:00');
INSERT INTO wms.sys_job_log (job_log_id, job_name, job_group, invoke_target, job_message, status, exception_info, create_time) VALUES (42, '库存预警检查', 'SYSTEM', 'stockWarningTask.checkStockWarning', '库存预警检查 总共耗时：35毫秒', '0', '', '2026-04-10 17:30:00');
INSERT INTO wms.sys_job_log (job_log_id, job_name, job_group, invoke_target, job_message, status, exception_info, create_time) VALUES (43, '库存预警检查', 'SYSTEM', 'stockWarningTask.checkStockWarning', '库存预警检查 总共耗时：93毫秒', '0', '', '2026-04-10 18:30:00');
INSERT INTO wms.sys_job_log (job_log_id, job_name, job_group, invoke_target, job_message, status, exception_info, create_time) VALUES (44, '库存预警检查', 'SYSTEM', 'stockWarningTask.checkStockWarning', '库存预警检查 总共耗时：24毫秒', '0', '', '2026-04-10 20:30:00');
INSERT INTO wms.sys_job_log (job_log_id, job_name, job_group, invoke_target, job_message, status, exception_info, create_time) VALUES (45, '库存预警检查', 'SYSTEM', 'stockWarningTask.checkStockWarning', '库存预警检查 总共耗时：32毫秒', '0', '', '2026-04-10 21:00:00');
INSERT INTO wms.sys_job_log (job_log_id, job_name, job_group, invoke_target, job_message, status, exception_info, create_time) VALUES (46, '库存预警检查', 'SYSTEM', 'stockWarningTask.checkStockWarning', '库存预警检查 总共耗时：23毫秒', '0', '', '2026-04-10 21:30:00');
INSERT INTO wms.sys_job_log (job_log_id, job_name, job_group, invoke_target, job_message, status, exception_info, create_time) VALUES (47, '库存预警检查', 'SYSTEM', 'stockWarningTask.checkStockWarning', '库存预警检查 总共耗时：40毫秒', '0', '', '2026-04-10 23:00:00');
INSERT INTO wms.sys_job_log (job_log_id, job_name, job_group, invoke_target, job_message, status, exception_info, create_time) VALUES (48, '库存预警检查', 'SYSTEM', 'stockWarningTask.checkStockWarning', '库存预警检查 总共耗时：49毫秒', '0', '', '2026-04-10 23:30:00');
INSERT INTO wms.sys_job_log (job_log_id, job_name, job_group, invoke_target, job_message, status, exception_info, create_time) VALUES (49, '库存预警检查', 'SYSTEM', 'stockWarningTask.checkStockWarning', '库存预警检查 总共耗时：43毫秒', '0', '', '2026-04-11 00:30:00');
INSERT INTO wms.sys_job_log (job_log_id, job_name, job_group, invoke_target, job_message, status, exception_info, create_time) VALUES (50, '库存预警检查', 'SYSTEM', 'stockWarningTask.checkStockWarning', '库存预警检查 总共耗时：33毫秒', '0', '', '2026-04-11 01:00:00');
INSERT INTO wms.sys_job_log (job_log_id, job_name, job_group, invoke_target, job_message, status, exception_info, create_time) VALUES (51, '库存预警检查', 'SYSTEM', 'stockWarningTask.checkStockWarning', '库存预警检查 总共耗时：108毫秒', '0', '', '2026-04-11 02:00:00');
INSERT INTO wms.sys_job_log (job_log_id, job_name, job_group, invoke_target, job_message, status, exception_info, create_time) VALUES (52, '库存预警检查', 'SYSTEM', 'stockWarningTask.checkStockWarning', '库存预警检查 总共耗时：42毫秒', '0', '', '2026-04-11 02:30:00');
INSERT INTO wms.sys_job_log (job_log_id, job_name, job_group, invoke_target, job_message, status, exception_info, create_time) VALUES (53, '库存预警检查', 'SYSTEM', 'stockWarningTask.checkStockWarning', '库存预警检查 总共耗时：33毫秒', '0', '', '2026-04-11 03:30:00');
INSERT INTO wms.sys_job_log (job_log_id, job_name, job_group, invoke_target, job_message, status, exception_info, create_time) VALUES (54, '库存预警检查', 'SYSTEM', 'stockWarningTask.checkStockWarning', '库存预警检查 总共耗时：36毫秒', '0', '', '2026-04-11 04:00:00');
INSERT INTO wms.sys_job_log (job_log_id, job_name, job_group, invoke_target, job_message, status, exception_info, create_time) VALUES (55, '库存预警检查', 'SYSTEM', 'stockWarningTask.checkStockWarning', '库存预警检查 总共耗时：87毫秒', '0', '', '2026-04-11 04:30:03');
INSERT INTO wms.sys_job_log (job_log_id, job_name, job_group, invoke_target, job_message, status, exception_info, create_time) VALUES (56, '库存预警检查', 'SYSTEM', 'stockWarningTask.checkStockWarning', '库存预警检查 总共耗时：45毫秒', '0', '', '2026-04-11 06:30:00');
INSERT INTO wms.sys_job_log (job_log_id, job_name, job_group, invoke_target, job_message, status, exception_info, create_time) VALUES (57, '库存预警检查', 'SYSTEM', 'stockWarningTask.checkStockWarning', '库存预警检查 总共耗时：43毫秒', '0', '', '2026-04-11 07:00:00');
INSERT INTO wms.sys_job_log (job_log_id, job_name, job_group, invoke_target, job_message, status, exception_info, create_time) VALUES (58, '库存预警检查', 'SYSTEM', 'stockWarningTask.checkStockWarning', '库存预警检查 总共耗时：28毫秒', '0', '', '2026-04-11 08:00:00');
INSERT INTO wms.sys_job_log (job_log_id, job_name, job_group, invoke_target, job_message, status, exception_info, create_time) VALUES (59, '库存预警检查', 'SYSTEM', 'stockWarningTask.checkStockWarning', '库存预警检查 总共耗时：31毫秒', '0', '', '2026-04-11 08:30:00');
INSERT INTO wms.sys_job_log (job_log_id, job_name, job_group, invoke_target, job_message, status, exception_info, create_time) VALUES (60, '库存预警检查', 'SYSTEM', 'stockWarningTask.checkStockWarning', '库存预警检查 总共耗时：81毫秒', '0', '', '2026-04-11 10:00:00');
INSERT INTO wms.sys_job_log (job_log_id, job_name, job_group, invoke_target, job_message, status, exception_info, create_time) VALUES (61, '库存预警检查', 'SYSTEM', 'stockWarningTask.checkStockWarning', '库存预警检查 总共耗时：42毫秒', '0', '', '2026-04-11 10:30:00');
INSERT INTO wms.sys_job_log (job_log_id, job_name, job_group, invoke_target, job_message, status, exception_info, create_time) VALUES (62, '库存预警检查', 'SYSTEM', 'stockWarningTask.checkStockWarning', '库存预警检查 总共耗时：23毫秒', '0', '', '2026-04-11 13:00:00');
INSERT INTO wms.sys_job_log (job_log_id, job_name, job_group, invoke_target, job_message, status, exception_info, create_time) VALUES (63, '库存预警检查', 'SYSTEM', 'stockWarningTask.checkStockWarning', '库存预警检查 总共耗时：44毫秒', '0', '', '2026-04-11 13:30:00');
INSERT INTO wms.sys_job_log (job_log_id, job_name, job_group, invoke_target, job_message, status, exception_info, create_time) VALUES (64, '库存预警检查', 'SYSTEM', 'stockWarningTask.checkStockWarning', '库存预警检查 总共耗时：24毫秒', '0', '', '2026-04-11 14:00:00');
INSERT INTO wms.sys_job_log (job_log_id, job_name, job_group, invoke_target, job_message, status, exception_info, create_time) VALUES (65, '库存预警检查', 'SYSTEM', 'stockWarningTask.checkStockWarning', '库存预警检查 总共耗时：66毫秒', '0', '', '2026-04-11 14:30:00');
INSERT INTO wms.sys_job_log (job_log_id, job_name, job_group, invoke_target, job_message, status, exception_info, create_time) VALUES (66, '库存预警检查', 'SYSTEM', 'stockWarningTask.checkStockWarning', '库存预警检查 总共耗时：25毫秒', '0', '', '2026-04-11 15:30:00');
INSERT INTO wms.sys_job_log (job_log_id, job_name, job_group, invoke_target, job_message, status, exception_info, create_time) VALUES (67, '库存预警检查', 'SYSTEM', 'stockWarningTask.checkStockWarning', '库存预警检查 总共耗时：40毫秒', '0', '', '2026-04-11 16:00:00');
INSERT INTO wms.sys_job_log (job_log_id, job_name, job_group, invoke_target, job_message, status, exception_info, create_time) VALUES (68, '库存预警检查', 'SYSTEM', 'stockWarningTask.checkStockWarning', '库存预警检查 总共耗时：69毫秒', '0', '', '2026-04-11 16:30:00');
INSERT INTO wms.sys_job_log (job_log_id, job_name, job_group, invoke_target, job_message, status, exception_info, create_time) VALUES (69, '库存预警检查', 'SYSTEM', 'stockWarningTask.checkStockWarning', '库存预警检查 总共耗时：61毫秒', '0', '', '2026-04-11 17:00:00');
INSERT INTO wms.sys_job_log (job_log_id, job_name, job_group, invoke_target, job_message, status, exception_info, create_time) VALUES (70, '库存预警检查', 'SYSTEM', 'stockWarningTask.checkStockWarning', '库存预警检查 总共耗时：55毫秒', '0', '', '2026-04-11 17:30:00');
INSERT INTO wms.sys_job_log (job_log_id, job_name, job_group, invoke_target, job_message, status, exception_info, create_time) VALUES (71, '库存预警检查', 'SYSTEM', 'stockWarningTask.checkStockWarning', '库存预警检查 总共耗时：133毫秒', '0', '', '2026-04-11 18:00:00');
INSERT INTO wms.sys_job_log (job_log_id, job_name, job_group, invoke_target, job_message, status, exception_info, create_time) VALUES (72, '库存预警检查', 'SYSTEM', 'stockWarningTask.checkStockWarning', '库存预警检查 总共耗时：41毫秒', '0', '', '2026-04-11 18:30:00');
INSERT INTO wms.sys_job_log (job_log_id, job_name, job_group, invoke_target, job_message, status, exception_info, create_time) VALUES (73, '库存预警检查', 'SYSTEM', 'stockWarningTask.checkStockWarning', '库存预警检查 总共耗时：75毫秒', '0', '', '2026-04-11 19:00:00');
INSERT INTO wms.sys_job_log (job_log_id, job_name, job_group, invoke_target, job_message, status, exception_info, create_time) VALUES (74, '库存预警检查', 'SYSTEM', 'stockWarningTask.checkStockWarning', '库存预警检查 总共耗时：21毫秒', '0', '', '2026-04-11 19:30:00');
INSERT INTO wms.sys_job_log (job_log_id, job_name, job_group, invoke_target, job_message, status, exception_info, create_time) VALUES (75, '库存预警检查', 'SYSTEM', 'stockWarningTask.checkStockWarning', '库存预警检查 总共耗时：19毫秒', '0', '', '2026-04-11 20:00:00');
INSERT INTO wms.sys_job_log (job_log_id, job_name, job_group, invoke_target, job_message, status, exception_info, create_time) VALUES (76, '库存预警检查', 'SYSTEM', 'stockWarningTask.checkStockWarning', '库存预警检查 总共耗时：17毫秒', '0', '', '2026-04-11 20:30:00');
INSERT INTO wms.sys_job_log (job_log_id, job_name, job_group, invoke_target, job_message, status, exception_info, create_time) VALUES (77, '库存预警检查', 'SYSTEM', 'stockWarningTask.checkStockWarning', '库存预警检查 总共耗时：65毫秒', '0', '', '2026-04-11 21:00:00');
INSERT INTO wms.sys_job_log (job_log_id, job_name, job_group, invoke_target, job_message, status, exception_info, create_time) VALUES (78, '库存预警检查', 'SYSTEM', 'stockWarningTask.checkStockWarning', '库存预警检查 总共耗时：36毫秒', '0', '', '2026-04-11 21:30:00');
INSERT INTO wms.sys_job_log (job_log_id, job_name, job_group, invoke_target, job_message, status, exception_info, create_time) VALUES (79, '库存预警检查', 'SYSTEM', 'stockWarningTask.checkStockWarning', '库存预警检查 总共耗时：66毫秒', '0', '', '2026-04-11 22:30:01');
INSERT INTO wms.sys_job_log (job_log_id, job_name, job_group, invoke_target, job_message, status, exception_info, create_time) VALUES (80, '库存预警检查', 'SYSTEM', 'stockWarningTask.checkStockWarning', '库存预警检查 总共耗时：187毫秒', '0', '', '2026-04-11 23:30:00');
INSERT INTO wms.sys_job_log (job_log_id, job_name, job_group, invoke_target, job_message, status, exception_info, create_time) VALUES (81, '库存预警检查', 'SYSTEM', 'stockWarningTask.checkStockWarning', '库存预警检查 总共耗时：36毫秒', '0', '', '2026-04-12 00:00:00');
INSERT INTO wms.sys_job_log (job_log_id, job_name, job_group, invoke_target, job_message, status, exception_info, create_time) VALUES (82, '库存预警检查', 'SYSTEM', 'stockWarningTask.checkStockWarning', '库存预警检查 总共耗时：29毫秒', '0', '', '2026-04-12 00:30:00');
INSERT INTO wms.sys_job_log (job_log_id, job_name, job_group, invoke_target, job_message, status, exception_info, create_time) VALUES (83, '设备定期维护检查', 'DEFAULT', 'equipmentMaintainTask.autoCreateMaintain()', '设备定期维护检查 总共耗时：13毫秒', '0', '', '2026-04-12 01:00:00');
INSERT INTO wms.sys_job_log (job_log_id, job_name, job_group, invoke_target, job_message, status, exception_info, create_time) VALUES (84, '库存预警检查', 'SYSTEM', 'stockWarningTask.checkStockWarning', '库存预警检查 总共耗时：20毫秒', '0', '', '2026-04-12 01:00:00');
INSERT INTO wms.sys_job_log (job_log_id, job_name, job_group, invoke_target, job_message, status, exception_info, create_time) VALUES (85, '库存预警检查', 'SYSTEM', 'stockWarningTask.checkStockWarning', '库存预警检查 总共耗时：13毫秒', '0', '', '2026-04-12 01:30:00');
INSERT INTO wms.sys_job_log (job_log_id, job_name, job_group, invoke_target, job_message, status, exception_info, create_time) VALUES (86, '库存预警检查', 'SYSTEM', 'stockWarningTask.checkStockWarning', '库存预警检查 总共耗时：9毫秒', '0', '', '2026-04-12 02:00:00');
INSERT INTO wms.sys_job_log (job_log_id, job_name, job_group, invoke_target, job_message, status, exception_info, create_time) VALUES (87, '库存预警检查', 'SYSTEM', 'stockWarningTask.checkStockWarning', '库存预警检查 总共耗时：44毫秒', '0', '', '2026-04-12 02:30:00');
INSERT INTO wms.sys_job_log (job_log_id, job_name, job_group, invoke_target, job_message, status, exception_info, create_time) VALUES (88, '订单异常预警检查', 'DEFAULT', 'orderWarningTask.checkOrderWarning()', '订单异常预警检查 总共耗时：15毫秒', '1', 'java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.ruoyi.quartz.util.JobInvokeUtil.invokeMethod(JobInvokeUtil.java:61)
	at com.ruoyi.quartz.util.JobInvokeUtil.invokeMethod(JobInvokeUtil.java:33)
	at com.ruoyi.quartz.util.QuartzDisallowConcurrentExecution.doExecute(QuartzDisallowConcurrentExecution.java:19)
	at com.ruoyi.quartz.util.AbstractQuartzJob.execute(AbstractQuartzJob.java:43)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: org.springframework.jdbc.BadSqlGrammarException: 
### Error querying database.  Cause: java.sql.SQLSyntaxErrorException: Unknown column \'plan_no\' in \'field list\'
### The error may exist in file [/Users/juedu/Downloads/MyCode/wms-platform/ruoyi-master/ruoyi-stock/target/classes/mapper/stock/StockProdOrderMapper.xml]
### The error may involve com.ruoyi.stock.mapper.StockProdOrderMapper.selectStockProdOrderList-Inline
### The error occurred while setting parameters
### SQL: select order_id, order_no, work_no, mat_code, mat_name, workshop_code, route_code, equipment_code, station_code, quantity, actual_quantity, priority, plan_start_date, plan_end_date, actual_start_date, actual_end_date, order_status, customer_order_no, plan_no, del_flag, create_by, create_time, update_by, update_time from stock_prod_order               WHERE del_flag = 0                                                                                                             ORDER BY priority DESC, create_time DESC
### Cause: java.sql.SQLSyntaxErrorException: Unknown column \'plan_no\' in \'field list\'
; bad SQL grammar []; nested exception is java.sql.SQLSyntaxErrorException: Unknown colum', '2026-04-12 03:00:00');
INSERT INTO wms.sys_job_log (job_log_id, job_name, job_group, invoke_target, job_message, status, exception_info, create_time) VALUES (89, '库存预警检查', 'SYSTEM', 'stockWarningTask.checkStockWarning', '库存预警检查 总共耗时：31毫秒', '0', '', '2026-04-12 03:00:00');
INSERT INTO wms.sys_job_log (job_log_id, job_name, job_group, invoke_target, job_message, status, exception_info, create_time) VALUES (90, '库存预警检查', 'SYSTEM', 'stockWarningTask.checkStockWarning', '库存预警检查 总共耗时：8毫秒', '0', '', '2026-04-12 03:30:00');
INSERT INTO wms.sys_job_log (job_log_id, job_name, job_group, invoke_target, job_message, status, exception_info, create_time) VALUES (91, '库存预警检查', 'SYSTEM', 'stockWarningTask.checkStockWarning', '库存预警检查 总共耗时：45毫秒', '0', '', '2026-04-12 04:00:00');
INSERT INTO wms.sys_job_log (job_log_id, job_name, job_group, invoke_target, job_message, status, exception_info, create_time) VALUES (92, '订单异常预警检查', 'DEFAULT', 'orderWarningTask.checkOrderWarning()', '订单异常预警检查 总共耗时：45毫秒', '0', '', '2026-04-12 04:00:00');
INSERT INTO wms.sys_job_log (job_log_id, job_name, job_group, invoke_target, job_message, status, exception_info, create_time) VALUES (93, '库存预警检查', 'SYSTEM', 'stockWarningTask.checkStockWarning', '库存预警检查 总共耗时：72毫秒', '0', '', '2026-04-12 04:30:00');
INSERT INTO wms.sys_job_log (job_log_id, job_name, job_group, invoke_target, job_message, status, exception_info, create_time) VALUES (94, '订单异常预警检查', 'DEFAULT', 'orderWarningTask.checkOrderWarning()', '订单异常预警检查 总共耗时：91毫秒', '0', '', '2026-04-12 05:00:00');
INSERT INTO wms.sys_job_log (job_log_id, job_name, job_group, invoke_target, job_message, status, exception_info, create_time) VALUES (95, '库存预警检查', 'SYSTEM', 'stockWarningTask.checkStockWarning', '库存预警检查 总共耗时：91毫秒', '0', '', '2026-04-12 05:00:00');
INSERT INTO wms.sys_job_log (job_log_id, job_name, job_group, invoke_target, job_message, status, exception_info, create_time) VALUES (96, '库存预警检查', 'SYSTEM', 'stockWarningTask.checkStockWarning', '库存预警检查 总共耗时：44毫秒', '0', '', '2026-04-12 05:30:00');
INSERT INTO wms.sys_job_log (job_log_id, job_name, job_group, invoke_target, job_message, status, exception_info, create_time) VALUES (97, '库存预警检查', 'SYSTEM', 'stockWarningTask.checkStockWarning', '库存预警检查 总共耗时：177毫秒', '0', '', '2026-04-12 16:00:00');
INSERT INTO wms.sys_job_log (job_log_id, job_name, job_group, invoke_target, job_message, status, exception_info, create_time) VALUES (98, '订单异常预警检查', 'DEFAULT', 'orderWarningTask.checkOrderWarning()', '订单异常预警检查 总共耗时：177毫秒', '0', '', '2026-04-12 16:00:00');
INSERT INTO wms.sys_job_log (job_log_id, job_name, job_group, invoke_target, job_message, status, exception_info, create_time) VALUES (99, '库存预警检查', 'SYSTEM', 'stockWarningTask.checkStockWarning', '库存预警检查 总共耗时：130毫秒', '0', '', '2026-04-12 16:30:00');
INSERT INTO wms.sys_job_log (job_log_id, job_name, job_group, invoke_target, job_message, status, exception_info, create_time) VALUES (100, '订单异常预警检查', 'DEFAULT', 'orderWarningTask.checkOrderWarning()', '订单异常预警检查 总共耗时：300毫秒', '0', '', '2026-04-12 17:00:00');
INSERT INTO wms.sys_job_log (job_log_id, job_name, job_group, invoke_target, job_message, status, exception_info, create_time) VALUES (101, '库存预警检查', 'SYSTEM', 'stockWarningTask.checkStockWarning', '库存预警检查 总共耗时：300毫秒', '0', '', '2026-04-12 17:00:00');
INSERT INTO wms.sys_job_log (job_log_id, job_name, job_group, invoke_target, job_message, status, exception_info, create_time) VALUES (102, '库存预警检查', 'SYSTEM', 'stockWarningTask.checkStockWarning', '库存预警检查 总共耗时：83毫秒', '0', '', '2026-04-12 17:30:00');
INSERT INTO wms.sys_job_log (job_log_id, job_name, job_group, invoke_target, job_message, status, exception_info, create_time) VALUES (103, '库存预警检查', 'SYSTEM', 'stockWarningTask.checkStockWarning', '库存预警检查 总共耗时：80毫秒', '0', '', '2026-04-12 18:00:00');
INSERT INTO wms.sys_job_log (job_log_id, job_name, job_group, invoke_target, job_message, status, exception_info, create_time) VALUES (104, '订单异常预警检查', 'DEFAULT', 'orderWarningTask.checkOrderWarning()', '订单异常预警检查 总共耗时：79毫秒', '0', '', '2026-04-12 18:00:00');
INSERT INTO wms.sys_job_log (job_log_id, job_name, job_group, invoke_target, job_message, status, exception_info, create_time) VALUES (105, '库存预警检查', 'SYSTEM', 'stockWarningTask.checkStockWarning', '库存预警检查 总共耗时：116毫秒', '0', '', '2026-04-12 18:30:00');
INSERT INTO wms.sys_job_log (job_log_id, job_name, job_group, invoke_target, job_message, status, exception_info, create_time) VALUES (106, '库存预警检查', 'SYSTEM', 'stockWarningTask.checkStockWarning', '库存预警检查 总共耗时：33毫秒', '0', '', '2026-04-12 19:00:00');
INSERT INTO wms.sys_job_log (job_log_id, job_name, job_group, invoke_target, job_message, status, exception_info, create_time) VALUES (107, '订单异常预警检查', 'DEFAULT', 'orderWarningTask.checkOrderWarning()', '订单异常预警检查 总共耗时：35毫秒', '0', '', '2026-04-12 19:00:00');
INSERT INTO wms.sys_job_log (job_log_id, job_name, job_group, invoke_target, job_message, status, exception_info, create_time) VALUES (108, '库存预警检查', 'SYSTEM', 'stockWarningTask.checkStockWarning', '库存预警检查 总共耗时：122毫秒', '0', '', '2026-04-12 19:30:00');
INSERT INTO wms.sys_job_log (job_log_id, job_name, job_group, invoke_target, job_message, status, exception_info, create_time) VALUES (109, '库存预警检查', 'SYSTEM', 'stockWarningTask.checkStockWarning', '库存预警检查 总共耗时：72毫秒', '0', '', '2026-04-12 20:00:00');
INSERT INTO wms.sys_job_log (job_log_id, job_name, job_group, invoke_target, job_message, status, exception_info, create_time) VALUES (110, '订单异常预警检查', 'DEFAULT', 'orderWarningTask.checkOrderWarning()', '订单异常预警检查 总共耗时：72毫秒', '0', '', '2026-04-12 20:00:00');
INSERT INTO wms.sys_job_log (job_log_id, job_name, job_group, invoke_target, job_message, status, exception_info, create_time) VALUES (111, '库存预警检查', 'SYSTEM', 'stockWarningTask.checkStockWarning', '库存预警检查 总共耗时：80毫秒', '0', '', '2026-04-12 23:00:01');
INSERT INTO wms.sys_job_log (job_log_id, job_name, job_group, invoke_target, job_message, status, exception_info, create_time) VALUES (112, '订单异常预警检查', 'DEFAULT', 'orderWarningTask.checkOrderWarning()', '订单异常预警检查 总共耗时：80毫秒', '0', '', '2026-04-12 23:00:01');
INSERT INTO wms.sys_job_log (job_log_id, job_name, job_group, invoke_target, job_message, status, exception_info, create_time) VALUES (113, '库存预警检查', 'SYSTEM', 'stockWarningTask.checkStockWarning', '库存预警检查 总共耗时：53毫秒', '0', '', '2026-04-13 00:30:00');
INSERT INTO wms.sys_job_log (job_log_id, job_name, job_group, invoke_target, job_message, status, exception_info, create_time) VALUES (114, '设备定期维护检查', 'DEFAULT', 'equipmentMaintainTask.autoCreateMaintain()', '设备定期维护检查 总共耗时：48毫秒', '0', '', '2026-04-13 01:00:00');
INSERT INTO wms.sys_job_log (job_log_id, job_name, job_group, invoke_target, job_message, status, exception_info, create_time) VALUES (115, '库存预警检查', 'SYSTEM', 'stockWarningTask.checkStockWarning', '库存预警检查 总共耗时：60毫秒', '0', '', '2026-04-13 01:00:00');
INSERT INTO wms.sys_job_log (job_log_id, job_name, job_group, invoke_target, job_message, status, exception_info, create_time) VALUES (116, '订单异常预警检查', 'DEFAULT', 'orderWarningTask.checkOrderWarning()', '订单异常预警检查 总共耗时：66毫秒', '0', '', '2026-04-13 01:00:00');
INSERT INTO wms.sys_job_log (job_log_id, job_name, job_group, invoke_target, job_message, status, exception_info, create_time) VALUES (117, '库存预警检查', 'SYSTEM', 'stockWarningTask.checkStockWarning', '库存预警检查 总共耗时：72毫秒', '0', '', '2026-04-13 02:30:00');
INSERT INTO wms.sys_job_log (job_log_id, job_name, job_group, invoke_target, job_message, status, exception_info, create_time) VALUES (118, '库存预警检查', 'SYSTEM', 'stockWarningTask.checkStockWarning', '库存预警检查 总共耗时：45毫秒', '0', '', '2026-04-13 03:00:00');
INSERT INTO wms.sys_job_log (job_log_id, job_name, job_group, invoke_target, job_message, status, exception_info, create_time) VALUES (119, '订单异常预警检查', 'DEFAULT', 'orderWarningTask.checkOrderWarning()', '订单异常预警检查 总共耗时：47毫秒', '0', '', '2026-04-13 03:00:00');
INSERT INTO wms.sys_job_log (job_log_id, job_name, job_group, invoke_target, job_message, status, exception_info, create_time) VALUES (120, '库存预警检查', 'SYSTEM', 'stockWarningTask.checkStockWarning', '库存预警检查 总共耗时：44毫秒', '0', '', '2026-04-13 04:30:00');
INSERT INTO wms.sys_job_log (job_log_id, job_name, job_group, invoke_target, job_message, status, exception_info, create_time) VALUES (121, '库存预警检查', 'SYSTEM', 'stockWarningTask.checkStockWarning', '库存预警检查 总共耗时：50毫秒', '0', '', '2026-04-13 05:00:00');
INSERT INTO wms.sys_job_log (job_log_id, job_name, job_group, invoke_target, job_message, status, exception_info, create_time) VALUES (122, '订单异常预警检查', 'DEFAULT', 'orderWarningTask.checkOrderWarning()', '订单异常预警检查 总共耗时：50毫秒', '0', '', '2026-04-13 05:00:00');
INSERT INTO wms.sys_job_log (job_log_id, job_name, job_group, invoke_target, job_message, status, exception_info, create_time) VALUES (123, '库存预警检查', 'SYSTEM', 'stockWarningTask.checkStockWarning', '库存预警检查 总共耗时：46毫秒', '0', '', '2026-04-13 06:30:00');
INSERT INTO wms.sys_job_log (job_log_id, job_name, job_group, invoke_target, job_message, status, exception_info, create_time) VALUES (124, '库存预警检查', 'SYSTEM', 'stockWarningTask.checkStockWarning', '库存预警检查 总共耗时：38毫秒', '0', '', '2026-04-13 07:00:00');
INSERT INTO wms.sys_job_log (job_log_id, job_name, job_group, invoke_target, job_message, status, exception_info, create_time) VALUES (125, '订单异常预警检查', 'DEFAULT', 'orderWarningTask.checkOrderWarning()', '订单异常预警检查 总共耗时：38毫秒', '0', '', '2026-04-13 07:00:00');
INSERT INTO wms.sys_job_log (job_log_id, job_name, job_group, invoke_target, job_message, status, exception_info, create_time) VALUES (126, '库存预警检查', 'SYSTEM', 'stockWarningTask.checkStockWarning', '库存预警检查 总共耗时：38毫秒', '0', '', '2026-04-13 07:30:00');
INSERT INTO wms.sys_job_log (job_log_id, job_name, job_group, invoke_target, job_message, status, exception_info, create_time) VALUES (127, '库存预警检查', 'SYSTEM', 'stockWarningTask.checkStockWarning', '库存预警检查 总共耗时：36毫秒', '0', '', '2026-04-13 08:00:00');
INSERT INTO wms.sys_job_log (job_log_id, job_name, job_group, invoke_target, job_message, status, exception_info, create_time) VALUES (128, '订单异常预警检查', 'DEFAULT', 'orderWarningTask.checkOrderWarning()', '订单异常预警检查 总共耗时：40毫秒', '0', '', '2026-04-13 08:00:00');
INSERT INTO wms.sys_job_log (job_log_id, job_name, job_group, invoke_target, job_message, status, exception_info, create_time) VALUES (129, '库存预警检查', 'SYSTEM', 'stockWarningTask.checkStockWarning', '库存预警检查 总共耗时：72毫秒', '0', '', '2026-04-13 08:30:00');
INSERT INTO wms.sys_job_log (job_log_id, job_name, job_group, invoke_target, job_message, status, exception_info, create_time) VALUES (130, '库存预警检查', 'SYSTEM', 'stockWarningTask.checkStockWarning', '库存预警检查 总共耗时：37毫秒', '0', '', '2026-04-13 09:00:00');
INSERT INTO wms.sys_job_log (job_log_id, job_name, job_group, invoke_target, job_message, status, exception_info, create_time) VALUES (131, '订单异常预警检查', 'DEFAULT', 'orderWarningTask.checkOrderWarning()', '订单异常预警检查 总共耗时：39毫秒', '0', '', '2026-04-13 09:00:00');
INSERT INTO wms.sys_job_log (job_log_id, job_name, job_group, invoke_target, job_message, status, exception_info, create_time) VALUES (132, '库存预警检查', 'SYSTEM', 'stockWarningTask.checkStockWarning', '库存预警检查 总共耗时：38毫秒', '0', '', '2026-04-13 09:30:00');
INSERT INTO wms.sys_job_log (job_log_id, job_name, job_group, invoke_target, job_message, status, exception_info, create_time) VALUES (133, '订单异常预警检查', 'DEFAULT', 'orderWarningTask.checkOrderWarning()', '订单异常预警检查 总共耗时：171毫秒', '0', '', '2026-04-13 10:00:00');
INSERT INTO wms.sys_job_log (job_log_id, job_name, job_group, invoke_target, job_message, status, exception_info, create_time) VALUES (134, '库存预警检查', 'SYSTEM', 'stockWarningTask.checkStockWarning', '库存预警检查 总共耗时：171毫秒', '0', '', '2026-04-13 10:00:00');
INSERT INTO wms.sys_job_log (job_log_id, job_name, job_group, invoke_target, job_message, status, exception_info, create_time) VALUES (135, '库存预警检查', 'SYSTEM', 'stockWarningTask.checkStockWarning', '库存预警检查 总共耗时：72毫秒', '0', '', '2026-04-13 10:30:00');
INSERT INTO wms.sys_job_log (job_log_id, job_name, job_group, invoke_target, job_message, status, exception_info, create_time) VALUES (136, '库存预警检查', 'SYSTEM', 'stockWarningTask.checkStockWarning', '库存预警检查 总共耗时：112毫秒', '0', '', '2026-04-13 11:00:00');
INSERT INTO wms.sys_job_log (job_log_id, job_name, job_group, invoke_target, job_message, status, exception_info, create_time) VALUES (137, '订单异常预警检查', 'DEFAULT', 'orderWarningTask.checkOrderWarning()', '订单异常预警检查 总共耗时：115毫秒', '0', '', '2026-04-13 11:00:00');
INSERT INTO wms.sys_job_log (job_log_id, job_name, job_group, invoke_target, job_message, status, exception_info, create_time) VALUES (138, '库存预警检查', 'SYSTEM', 'stockWarningTask.checkStockWarning', '库存预警检查 总共耗时：76毫秒', '0', '', '2026-04-13 11:30:00');
INSERT INTO wms.sys_job_log (job_log_id, job_name, job_group, invoke_target, job_message, status, exception_info, create_time) VALUES (139, '库存预警检查', 'SYSTEM', 'stockWarningTask.checkStockWarning', '库存预警检查 总共耗时：104毫秒', '0', '', '2026-04-13 12:00:00');
INSERT INTO wms.sys_job_log (job_log_id, job_name, job_group, invoke_target, job_message, status, exception_info, create_time) VALUES (140, '订单异常预警检查', 'DEFAULT', 'orderWarningTask.checkOrderWarning()', '订单异常预警检查 总共耗时：105毫秒', '0', '', '2026-04-13 12:00:00');
INSERT INTO wms.sys_job_log (job_log_id, job_name, job_group, invoke_target, job_message, status, exception_info, create_time) VALUES (141, '库存预警检查', 'SYSTEM', 'stockWarningTask.checkStockWarning', '库存预警检查 总共耗时：166毫秒', '0', '', '2026-04-13 12:30:00');
INSERT INTO wms.sys_job_log (job_log_id, job_name, job_group, invoke_target, job_message, status, exception_info, create_time) VALUES (142, '库存预警检查', 'SYSTEM', 'stockWarningTask.checkStockWarning', '库存预警检查 总共耗时：38毫秒', '0', '', '2026-04-13 13:00:00');
INSERT INTO wms.sys_job_log (job_log_id, job_name, job_group, invoke_target, job_message, status, exception_info, create_time) VALUES (143, '订单异常预警检查', 'DEFAULT', 'orderWarningTask.checkOrderWarning()', '订单异常预警检查 总共耗时：47毫秒', '0', '', '2026-04-13 13:00:00');
INSERT INTO wms.sys_job_log (job_log_id, job_name, job_group, invoke_target, job_message, status, exception_info, create_time) VALUES (144, '库存预警检查', 'SYSTEM', 'stockWarningTask.checkStockWarning', '库存预警检查 总共耗时：65毫秒', '0', '', '2026-04-13 13:30:00');
INSERT INTO wms.sys_job_log (job_log_id, job_name, job_group, invoke_target, job_message, status, exception_info, create_time) VALUES (145, '库存预警检查', 'SYSTEM', 'stockWarningTask.checkStockWarning', '库存预警检查 总共耗时：73毫秒', '0', '', '2026-04-13 14:00:00');
INSERT INTO wms.sys_job_log (job_log_id, job_name, job_group, invoke_target, job_message, status, exception_info, create_time) VALUES (146, '订单异常预警检查', 'DEFAULT', 'orderWarningTask.checkOrderWarning()', '订单异常预警检查 总共耗时：72毫秒', '0', '', '2026-04-13 14:00:00');
INSERT INTO wms.sys_job_log (job_log_id, job_name, job_group, invoke_target, job_message, status, exception_info, create_time) VALUES (147, '库存预警检查', 'SYSTEM', 'stockWarningTask.checkStockWarning', '库存预警检查 总共耗时：107毫秒', '0', '', '2026-04-13 14:30:00');
INSERT INTO wms.sys_job_log (job_log_id, job_name, job_group, invoke_target, job_message, status, exception_info, create_time) VALUES (148, '订单异常预警检查', 'DEFAULT', 'orderWarningTask.checkOrderWarning()', '订单异常预警检查 总共耗时：94毫秒', '0', '', '2026-04-13 15:00:00');
INSERT INTO wms.sys_job_log (job_log_id, job_name, job_group, invoke_target, job_message, status, exception_info, create_time) VALUES (149, '库存预警检查', 'SYSTEM', 'stockWarningTask.checkStockWarning', '库存预警检查 总共耗时：94毫秒', '0', '', '2026-04-13 15:00:00');
INSERT INTO wms.sys_job_log (job_log_id, job_name, job_group, invoke_target, job_message, status, exception_info, create_time) VALUES (150, '库存预警检查', 'SYSTEM', 'stockWarningTask.checkStockWarning', '库存预警检查 总共耗时：106毫秒', '0', '', '2026-04-13 15:30:00');
INSERT INTO wms.sys_job_log (job_log_id, job_name, job_group, invoke_target, job_message, status, exception_info, create_time) VALUES (151, '订单异常预警检查', 'DEFAULT', 'orderWarningTask.checkOrderWarning()', '订单异常预警检查 总共耗时：90毫秒', '0', '', '2026-04-13 16:00:00');
INSERT INTO wms.sys_job_log (job_log_id, job_name, job_group, invoke_target, job_message, status, exception_info, create_time) VALUES (152, '库存预警检查', 'SYSTEM', 'stockWarningTask.checkStockWarning', '库存预警检查 总共耗时：90毫秒', '0', '', '2026-04-13 16:00:00');
INSERT INTO wms.sys_job_log (job_log_id, job_name, job_group, invoke_target, job_message, status, exception_info, create_time) VALUES (153, '库存预警检查', 'SYSTEM', 'stockWarningTask.checkStockWarning', '库存预警检查 总共耗时：89毫秒', '0', '', '2026-04-13 16:30:00');
INSERT INTO wms.sys_job_log (job_log_id, job_name, job_group, invoke_target, job_message, status, exception_info, create_time) VALUES (154, '库存预警检查', 'SYSTEM', 'stockWarningTask.checkStockWarning', '库存预警检查 总共耗时：103毫秒', '0', '', '2026-04-13 17:00:00');
INSERT INTO wms.sys_job_log (job_log_id, job_name, job_group, invoke_target, job_message, status, exception_info, create_time) VALUES (155, '订单异常预警检查', 'DEFAULT', 'orderWarningTask.checkOrderWarning()', '订单异常预警检查 总共耗时：103毫秒', '0', '', '2026-04-13 17:00:00');
INSERT INTO wms.sys_job_log (job_log_id, job_name, job_group, invoke_target, job_message, status, exception_info, create_time) VALUES (156, '订单异常预警检查', 'DEFAULT', 'orderWarningTask.checkOrderWarning()', '订单异常预警检查 总共耗时：171毫秒', '0', '', '2026-04-13 18:00:00');
INSERT INTO wms.sys_job_log (job_log_id, job_name, job_group, invoke_target, job_message, status, exception_info, create_time) VALUES (157, '库存预警检查', 'SYSTEM', 'stockWarningTask.checkStockWarning', '库存预警检查 总共耗时：171毫秒', '0', '', '2026-04-13 18:00:00');
INSERT INTO wms.sys_job_log (job_log_id, job_name, job_group, invoke_target, job_message, status, exception_info, create_time) VALUES (158, '库存预警检查', 'SYSTEM', 'stockWarningTask.checkStockWarning', '库存预警检查 总共耗时：82毫秒', '0', '', '2026-04-13 18:30:00');
INSERT INTO wms.sys_job_log (job_log_id, job_name, job_group, invoke_target, job_message, status, exception_info, create_time) VALUES (159, '库存预警检查', 'SYSTEM', 'stockWarningTask.checkStockWarning', '库存预警检查 总共耗时：75毫秒', '0', '', '2026-04-13 19:00:00');
INSERT INTO wms.sys_job_log (job_log_id, job_name, job_group, invoke_target, job_message, status, exception_info, create_time) VALUES (160, '订单异常预警检查', 'DEFAULT', 'orderWarningTask.checkOrderWarning()', '订单异常预警检查 总共耗时：76毫秒', '0', '', '2026-04-13 19:00:00');
