create table sys_dict_data
(
    dict_code   bigint auto_increment comment '字典编码'
        primary key,
    dict_sort   int          default 0   null comment '字典排序',
    dict_label  varchar(100) default ''  null comment '字典标签',
    dict_value  varchar(100) default ''  null comment '字典键值',
    dict_type   varchar(100) default ''  null comment '字典类型',
    css_class   varchar(100)             null comment '样式属性（其他样式扩展）',
    list_class  varchar(100)             null comment '表格回显样式',
    is_default  char         default 'N' null comment '是否默认（Y是 N否）',
    status      char         default '0' null comment '状态（0正常 1停用）',
    create_by   varchar(64)  default ''  null comment '创建者',
    create_time datetime                 null comment '创建时间',
    update_by   varchar(64)  default ''  null comment '更新者',
    update_time datetime                 null comment '更新时间',
    remark      varchar(500)             null comment '备注'
)
    comment '字典数据表' collate = utf8mb4_general_ci
                         row_format = DYNAMIC;

INSERT INTO wms.sys_dict_data (dict_code, dict_sort, dict_label, dict_value, dict_type, css_class, list_class, is_default, status, create_by, create_time, update_by, update_time, remark) VALUES (1, 1, '男', '0', 'sys_user_sex', '', '', 'Y', '0', 'admin', '2022-07-10 01:24:56', '', null, '性别男');
INSERT INTO wms.sys_dict_data (dict_code, dict_sort, dict_label, dict_value, dict_type, css_class, list_class, is_default, status, create_by, create_time, update_by, update_time, remark) VALUES (2, 2, '女', '1', 'sys_user_sex', '', '', 'N', '0', 'admin', '2022-07-10 01:24:56', '', null, '性别女');
INSERT INTO wms.sys_dict_data (dict_code, dict_sort, dict_label, dict_value, dict_type, css_class, list_class, is_default, status, create_by, create_time, update_by, update_time, remark) VALUES (3, 3, '未知', '2', 'sys_user_sex', '', '', 'N', '0', 'admin', '2022-07-10 01:24:56', '', null, '性别未知');
INSERT INTO wms.sys_dict_data (dict_code, dict_sort, dict_label, dict_value, dict_type, css_class, list_class, is_default, status, create_by, create_time, update_by, update_time, remark) VALUES (4, 1, '显示', '0', 'sys_show_hide', '', 'primary', 'Y', '0', 'admin', '2022-07-10 01:24:56', '', null, '显示菜单');
INSERT INTO wms.sys_dict_data (dict_code, dict_sort, dict_label, dict_value, dict_type, css_class, list_class, is_default, status, create_by, create_time, update_by, update_time, remark) VALUES (5, 2, '隐藏', '1', 'sys_show_hide', '', 'danger', 'N', '0', 'admin', '2022-07-10 01:24:56', '', null, '隐藏菜单');
INSERT INTO wms.sys_dict_data (dict_code, dict_sort, dict_label, dict_value, dict_type, css_class, list_class, is_default, status, create_by, create_time, update_by, update_time, remark) VALUES (6, 1, '正常', '0', 'sys_normal_disable', '', 'primary', 'Y', '0', 'admin', '2022-07-10 01:24:56', '', null, '正常状态');
INSERT INTO wms.sys_dict_data (dict_code, dict_sort, dict_label, dict_value, dict_type, css_class, list_class, is_default, status, create_by, create_time, update_by, update_time, remark) VALUES (7, 2, '停用', '1', 'sys_normal_disable', '', 'danger', 'N', '0', 'admin', '2022-07-10 01:24:56', '', null, '停用状态');
INSERT INTO wms.sys_dict_data (dict_code, dict_sort, dict_label, dict_value, dict_type, css_class, list_class, is_default, status, create_by, create_time, update_by, update_time, remark) VALUES (8, 1, '正常', '0', 'sys_job_status', '', 'primary', 'Y', '0', 'admin', '2022-07-10 01:24:56', '', null, '正常状态');
INSERT INTO wms.sys_dict_data (dict_code, dict_sort, dict_label, dict_value, dict_type, css_class, list_class, is_default, status, create_by, create_time, update_by, update_time, remark) VALUES (9, 2, '暂停', '1', 'sys_job_status', '', 'danger', 'N', '0', 'admin', '2022-07-10 01:24:56', '', null, '停用状态');
INSERT INTO wms.sys_dict_data (dict_code, dict_sort, dict_label, dict_value, dict_type, css_class, list_class, is_default, status, create_by, create_time, update_by, update_time, remark) VALUES (10, 1, '默认', 'DEFAULT', 'sys_job_group', '', '', 'Y', '0', 'admin', '2022-07-10 01:24:56', '', null, '默认分组');
INSERT INTO wms.sys_dict_data (dict_code, dict_sort, dict_label, dict_value, dict_type, css_class, list_class, is_default, status, create_by, create_time, update_by, update_time, remark) VALUES (11, 2, '系统', 'SYSTEM', 'sys_job_group', '', '', 'N', '0', 'admin', '2022-07-10 01:24:56', '', null, '系统分组');
INSERT INTO wms.sys_dict_data (dict_code, dict_sort, dict_label, dict_value, dict_type, css_class, list_class, is_default, status, create_by, create_time, update_by, update_time, remark) VALUES (12, 1, '是', 'Y', 'sys_yes_no', '', 'primary', 'Y', '0', 'admin', '2022-07-10 01:24:56', '', null, '系统默认是');
INSERT INTO wms.sys_dict_data (dict_code, dict_sort, dict_label, dict_value, dict_type, css_class, list_class, is_default, status, create_by, create_time, update_by, update_time, remark) VALUES (13, 2, '否', 'N', 'sys_yes_no', '', 'danger', 'N', '0', 'admin', '2022-07-10 01:24:56', '', null, '系统默认否');
INSERT INTO wms.sys_dict_data (dict_code, dict_sort, dict_label, dict_value, dict_type, css_class, list_class, is_default, status, create_by, create_time, update_by, update_time, remark) VALUES (14, 1, '通知', '1', 'sys_notice_type', '', 'warning', 'Y', '0', 'admin', '2022-07-10 01:24:56', '', null, '通知');
INSERT INTO wms.sys_dict_data (dict_code, dict_sort, dict_label, dict_value, dict_type, css_class, list_class, is_default, status, create_by, create_time, update_by, update_time, remark) VALUES (15, 2, '公告', '2', 'sys_notice_type', '', 'success', 'N', '0', 'admin', '2022-07-10 01:24:56', '', null, '公告');
INSERT INTO wms.sys_dict_data (dict_code, dict_sort, dict_label, dict_value, dict_type, css_class, list_class, is_default, status, create_by, create_time, update_by, update_time, remark) VALUES (16, 1, '正常', '0', 'sys_notice_status', '', 'primary', 'Y', '0', 'admin', '2022-07-10 01:24:56', '', null, '正常状态');
INSERT INTO wms.sys_dict_data (dict_code, dict_sort, dict_label, dict_value, dict_type, css_class, list_class, is_default, status, create_by, create_time, update_by, update_time, remark) VALUES (17, 2, '关闭', '1', 'sys_notice_status', '', 'danger', 'N', '0', 'admin', '2022-07-10 01:24:56', '', null, '关闭状态');
INSERT INTO wms.sys_dict_data (dict_code, dict_sort, dict_label, dict_value, dict_type, css_class, list_class, is_default, status, create_by, create_time, update_by, update_time, remark) VALUES (18, 1, '新增', '1', 'sys_oper_type', '', 'info', 'N', '0', 'admin', '2022-07-10 01:24:56', '', null, '新增操作');
INSERT INTO wms.sys_dict_data (dict_code, dict_sort, dict_label, dict_value, dict_type, css_class, list_class, is_default, status, create_by, create_time, update_by, update_time, remark) VALUES (19, 2, '修改', '2', 'sys_oper_type', '', 'info', 'N', '0', 'admin', '2022-07-10 01:24:56', '', null, '修改操作');
INSERT INTO wms.sys_dict_data (dict_code, dict_sort, dict_label, dict_value, dict_type, css_class, list_class, is_default, status, create_by, create_time, update_by, update_time, remark) VALUES (20, 3, '删除', '3', 'sys_oper_type', '', 'danger', 'N', '0', 'admin', '2022-07-10 01:24:56', '', null, '删除操作');
INSERT INTO wms.sys_dict_data (dict_code, dict_sort, dict_label, dict_value, dict_type, css_class, list_class, is_default, status, create_by, create_time, update_by, update_time, remark) VALUES (21, 4, '授权', '4', 'sys_oper_type', '', 'primary', 'N', '0', 'admin', '2022-07-10 01:24:56', '', null, '授权操作');
INSERT INTO wms.sys_dict_data (dict_code, dict_sort, dict_label, dict_value, dict_type, css_class, list_class, is_default, status, create_by, create_time, update_by, update_time, remark) VALUES (22, 5, '导出', '5', 'sys_oper_type', '', 'warning', 'N', '0', 'admin', '2022-07-10 01:24:56', '', null, '导出操作');
INSERT INTO wms.sys_dict_data (dict_code, dict_sort, dict_label, dict_value, dict_type, css_class, list_class, is_default, status, create_by, create_time, update_by, update_time, remark) VALUES (23, 6, '导入', '6', 'sys_oper_type', '', 'warning', 'N', '0', 'admin', '2022-07-10 01:24:56', '', null, '导入操作');
INSERT INTO wms.sys_dict_data (dict_code, dict_sort, dict_label, dict_value, dict_type, css_class, list_class, is_default, status, create_by, create_time, update_by, update_time, remark) VALUES (24, 7, '强退', '7', 'sys_oper_type', '', 'danger', 'N', '0', 'admin', '2022-07-10 01:24:56', '', null, '强退操作');
INSERT INTO wms.sys_dict_data (dict_code, dict_sort, dict_label, dict_value, dict_type, css_class, list_class, is_default, status, create_by, create_time, update_by, update_time, remark) VALUES (25, 8, '生成代码', '8', 'sys_oper_type', '', 'warning', 'N', '0', 'admin', '2022-07-10 01:24:56', '', null, '生成操作');
INSERT INTO wms.sys_dict_data (dict_code, dict_sort, dict_label, dict_value, dict_type, css_class, list_class, is_default, status, create_by, create_time, update_by, update_time, remark) VALUES (26, 9, '清空数据', '9', 'sys_oper_type', '', 'danger', 'N', '0', 'admin', '2022-07-10 01:24:56', '', null, '清空操作');
INSERT INTO wms.sys_dict_data (dict_code, dict_sort, dict_label, dict_value, dict_type, css_class, list_class, is_default, status, create_by, create_time, update_by, update_time, remark) VALUES (27, 1, '成功', '0', 'sys_common_status', '', 'primary', 'N', '0', 'admin', '2022-07-10 01:24:56', '', null, '正常状态');
INSERT INTO wms.sys_dict_data (dict_code, dict_sort, dict_label, dict_value, dict_type, css_class, list_class, is_default, status, create_by, create_time, update_by, update_time, remark) VALUES (28, 2, '失败', '1', 'sys_common_status', '', 'danger', 'N', '0', 'admin', '2022-07-10 01:24:56', '', null, '停用状态');
INSERT INTO wms.sys_dict_data (dict_code, dict_sort, dict_label, dict_value, dict_type, css_class, list_class, is_default, status, create_by, create_time, update_by, update_time, remark) VALUES (110, 1, '箱', 'PCS', 'base_mat_unit', null, 'default', 'N', '0', 'admin', '2022-07-24 06:02:32', 'admin', '2022-07-24 06:05:19', null);
INSERT INTO wms.sys_dict_data (dict_code, dict_sort, dict_label, dict_value, dict_type, css_class, list_class, is_default, status, create_by, create_time, update_by, update_time, remark) VALUES (111, 2, '吨', 'T', 'base_mat_unit', null, 'default', 'N', '0', 'admin', '2022-07-24 06:02:50', '', null, null);
INSERT INTO wms.sys_dict_data (dict_code, dict_sort, dict_label, dict_value, dict_type, css_class, list_class, is_default, status, create_by, create_time, update_by, update_time, remark) VALUES (112, 3, '件', 'UNIT', 'base_mat_unit', null, 'default', 'N', '0', 'admin', '2022-07-24 06:12:53', '', null, null);
INSERT INTO wms.sys_dict_data (dict_code, dict_sort, dict_label, dict_value, dict_type, css_class, list_class, is_default, status, create_by, create_time, update_by, update_time, remark) VALUES (113, 1, '原材料仓库', 'raw_material', 'warehouse_type', '', 'primary', 'N', '0', 'admin', '2026-03-31 18:19:43', '', null, '存放原材料的仓库');
INSERT INTO wms.sys_dict_data (dict_code, dict_sort, dict_label, dict_value, dict_type, css_class, list_class, is_default, status, create_by, create_time, update_by, update_time, remark) VALUES (114, 2, '成品仓库', 'finished_product', 'warehouse_type', '', 'success', 'N', '0', 'admin', '2026-03-31 18:19:43', '', null, '存放成品的仓库');
INSERT INTO wms.sys_dict_data (dict_code, dict_sort, dict_label, dict_value, dict_type, css_class, list_class, is_default, status, create_by, create_time, update_by, update_time, remark) VALUES (115, 3, '半成品仓库', 'semi_finished', 'warehouse_type', '', 'info', 'N', '0', 'admin', '2026-03-31 18:19:43', '', null, '存放半成品的仓库');
INSERT INTO wms.sys_dict_data (dict_code, dict_sort, dict_label, dict_value, dict_type, css_class, list_class, is_default, status, create_by, create_time, update_by, update_time, remark) VALUES (116, 4, '辅料仓库', 'auxiliary', 'warehouse_type', '', 'warning', 'N', '0', 'admin', '2026-03-31 18:19:43', '', null, '存放辅助材料的仓库');
INSERT INTO wms.sys_dict_data (dict_code, dict_sort, dict_label, dict_value, dict_type, css_class, list_class, is_default, status, create_by, create_time, update_by, update_time, remark) VALUES (117, 5, '包材仓库', 'packaging', 'warehouse_type', '', 'warning', 'N', '0', 'admin', '2026-03-31 18:19:43', '', null, '存放包装材料的仓库');
INSERT INTO wms.sys_dict_data (dict_code, dict_sort, dict_label, dict_value, dict_type, css_class, list_class, is_default, status, create_by, create_time, update_by, update_time, remark) VALUES (118, 6, '五金仓库', 'hardware', 'warehouse_type', '', 'default', 'N', '0', 'admin', '2026-03-31 18:19:43', '', null, '存放五金配件的仓库');
INSERT INTO wms.sys_dict_data (dict_code, dict_sort, dict_label, dict_value, dict_type, css_class, list_class, is_default, status, create_by, create_time, update_by, update_time, remark) VALUES (119, 7, '危化品仓库', 'dangerous', 'warehouse_type', '', 'danger', 'N', '0', 'admin', '2026-03-31 18:19:43', '', null, '存放危险化学品的仓库');
INSERT INTO wms.sys_dict_data (dict_code, dict_sort, dict_label, dict_value, dict_type, css_class, list_class, is_default, status, create_by, create_time, update_by, update_time, remark) VALUES (120, 8, '电子元件仓库', 'electronic', 'warehouse_type', '', 'default', 'N', '0', 'admin', '2026-03-31 18:19:43', '', null, '存放电子元器件的仓库');
INSERT INTO wms.sys_dict_data (dict_code, dict_sort, dict_label, dict_value, dict_type, css_class, list_class, is_default, status, create_by, create_time, update_by, update_time, remark) VALUES (121, 9, '综合仓库', 'general', 'warehouse_type', '', 'default', 'N', '0', 'admin', '2026-03-31 18:19:43', '', null, '混合存储的仓库');
INSERT INTO wms.sys_dict_data (dict_code, dict_sort, dict_label, dict_value, dict_type, css_class, list_class, is_default, status, create_by, create_time, update_by, update_time, remark) VALUES (200, 1, '启用', '0', 'mat_label_status', '', 'success', 'Y', '0', 'admin', '2026-04-08 11:46:21', '', null, '标签启用');
INSERT INTO wms.sys_dict_data (dict_code, dict_sort, dict_label, dict_value, dict_type, css_class, list_class, is_default, status, create_by, create_time, update_by, update_time, remark) VALUES (201, 2, '停用', '1', 'mat_label_status', '', 'danger', 'N', '0', 'admin', '2026-04-08 11:46:21', '', null, '标签停用');
INSERT INTO wms.sys_dict_data (dict_code, dict_sort, dict_label, dict_value, dict_type, css_class, list_class, is_default, status, create_by, create_time, update_by, update_time, remark) VALUES (202, 4, '平方米', 'SQUARE_METER', 'base_mat_unit', null, 'default', 'N', '0', 'admin', '2026-04-08 18:45:18', '', null, null);
INSERT INTO wms.sys_dict_data (dict_code, dict_sort, dict_label, dict_value, dict_type, css_class, list_class, is_default, status, create_by, create_time, update_by, update_time, remark) VALUES (203, 5, '片', 'PIECE', 'base_mat_unit', null, 'default', 'N', '0', 'admin', '2026-04-08 18:45:18', '', null, null);
INSERT INTO wms.sys_dict_data (dict_code, dict_sort, dict_label, dict_value, dict_type, css_class, list_class, is_default, status, create_by, create_time, update_by, update_time, remark) VALUES (204, 6, '千克', 'KG', 'base_mat_unit', null, 'default', 'N', '0', 'admin', '2026-04-08 18:45:18', '', null, null);
INSERT INTO wms.sys_dict_data (dict_code, dict_sort, dict_label, dict_value, dict_type, css_class, list_class, is_default, status, create_by, create_time, update_by, update_time, remark) VALUES (205, 7, '升', 'LITER', 'base_mat_unit', null, 'default', 'N', '0', 'admin', '2026-04-08 18:45:18', '', null, null);
INSERT INTO wms.sys_dict_data (dict_code, dict_sort, dict_label, dict_value, dict_type, css_class, list_class, is_default, status, create_by, create_time, update_by, update_time, remark) VALUES (206, 8, '米', 'METER', 'base_mat_unit', null, 'default', 'N', '0', 'admin', '2026-04-08 18:45:18', '', null, null);
INSERT INTO wms.sys_dict_data (dict_code, dict_sort, dict_label, dict_value, dict_type, css_class, list_class, is_default, status, create_by, create_time, update_by, update_time, remark) VALUES (207, 9, '张', 'SHEET', 'base_mat_unit', null, 'default', 'N', '0', 'admin', '2026-04-08 18:45:18', '', null, null);
INSERT INTO wms.sys_dict_data (dict_code, dict_sort, dict_label, dict_value, dict_type, css_class, list_class, is_default, status, create_by, create_time, update_by, update_time, remark) VALUES (208, 10, '卷', 'ROLL', 'base_mat_unit', null, 'default', 'N', '0', 'admin', '2026-04-08 18:45:18', '', null, null);
